version: "3.3"
services:
#Registry
  registry:
    image: registry:2
    name: private-registry
    restart: always
    ports:
    - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - /root/docker_data/image:/var/lib/registry
      - /root/docker_data/certs:/certs
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  registrydata:
    driver: local